name: build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      -
         name: Install dependencies
         run: yarn
      -
         name: build dist
         run: yarn build
      -
        name: Upload artifacts dist
        uses: actions/upload-artifact@v2
        with: 
          name: dist
          path: dist
